services:
  db_users:
    image: postgres:13
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  db_crud:
    image: postgres:13
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - crud_db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_users
      - db_crud

volumes:
  users_db_data:
  crud_db_data: